#ifndef CONSTANTS_H
#define CONSTANTS_H


#define DEFAULT_VALUE 0
#define PATH_TO_CONFIG_FILE "./Data.json"
#define ZERO_PERSENT 0
#define HUNDRED_PERSENT 100
#define MIN_SHORT_BREAK 3
#define MAX_SHORT_BREAK 6
#define MIN_LONG_BREAK 10
#define MAX_LONG_BREAK 35
#define MIN_TIME_OF_WORK 15
#define MAX_TIME_OF_WORK 50
#define INCREMENT_OF_LONG_BREAK 5
#define INCREMENT_OF_LONG_POMODORO 5

#define COUNTOFPOMODORO   4
#define TIMERINTERVAL     1000


#endif // CONSTANTS_H
